language: c

jobs:
  include:
  - os: linux
    dist: xenial
    arch: arm64
    compiler: gcc
    env: BUILD_SYSTEM="autotools" CONFIGURE_OPTS=
  - os: linux
    dist: xenial
    arch: arm64
    compiler: clang
    env: BUILD_SYSTEM="autotools" CONFIGURE_OPTS=
  - os: linux
    dist: focal
    arch: arm64
    compiler: gcc
    env: BUILD_SYSTEM="cmake" CONFIGURE_OPTS=
  - os: linux
    dist: focal
    arch: arm64
    compiler: clang
    env: BUILD_SYSTEM="cmake" CONFIGURE_OPTS=
  - os: linux
    dist: xenial
    arch: ppc64le
    compiler: gcc
    env: BUILD_SYSTEM="autotools" CONFIGURE_OPTS=
  - os: linux
    dist: xenial
    arch: ppc64le
    compiler: clang
    env: BUILD_SYSTEM="autotools" CONFIGURE_OPTS=
  - os: linux
    dist: focal
    arch: ppc64le
    compiler: gcc
    env: BUILD_SYSTEM="cmake" CONFIGURE_OPTS=
  - os: linux
    dist: focal
    arch: ppc64le
    compiler: clang
    env: BUILD_SYSTEM="cmake" CONFIGURE_OPTS=

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -y install libtool-bin libogg-dev doxygen libxml2-utils w3c-sgml-lib; fi

script:
  - if [[ "${BUILD_SYSTEM}" == "autotools" ]]; then ./autogen.sh && ./configure $CONFIGURE_OPTS && make && make check; fi
  - if [[ "${BUILD_SYSTEM}" == "cmake" ]]; then mkdir cmake-build && cd cmake-build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON $CONFIGURE_OPTS && cmake --build . && ctest -V; fi
